# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"

group :jekyll_plugins do
   gem "jekyll-menus", :git => "https://github.com/forestryio/jekyll-menus.git"  # <---- IT GOES HERE
end